from flask import Flask, render_template, request, send_from_directory
from parser import LogParser
from analyzer import ThreatDetector
from visualizer import GraphMaker
import os

# 1. Initialize the Flask app object first
app = Flask(__name__)

# 2. Configure Vercel-friendly paths
# Vercel's environment is read-only; /tmp is the only writable directory
UPLOAD_FOLDER = '/tmp'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

@app.route('/', methods=['GET', 'POST'])
def home():
    threats = {}
    
    if request.method == 'POST':
        # Check if the post request has the file part
        if 'logfile' not in request.files:
            return render_template('index.html', threats={}, uploaded=False)
            
        file = request.files['logfile']
        
        if file.filename != '':
            # Save the uploaded file to the /tmp directory
            filepath = os.path.join(app.config['UPLOAD_FOLDER'], 'uploaded_server.log')
            file.save(filepath)

            # Process the log file using the assigned student modules
            # LogParser handles file reading and splitting [cite: 11, 12, 14]
            parser = LogParser(filepath)
            clean_data = parser.read_logs()

            # ThreatDetector uses Pandas/NumPy to identify Brute Force and DDoS [cite: 18, 19, 22]
            detector = ThreatDetector(clean_data)
            threats = detector.find_threats()

            # GraphMaker generates the visualization [cite: 2, 4, 6]
            visuals = GraphMaker(threats)
            visuals.plot_top_threats()

            return render_template('index.html', threats=threats, uploaded=True)

    return render_template('index.html', threats={}, uploaded=False)

# 3. Dedicated route to serve the graph from /tmp
@app.route('/get_report')
def get_report():
    # Serves the .png file generated by visualizer.py from the temporary directory
    return send_from_directory(UPLOAD_FOLDER, 'threat_report.png')

# 4. Mandatory export for Vercel's Python runtime
app = app

if __name__ == '__main__':
    # Standard local execution for testing in VS Code
    app.run(debug=True)
